// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: snapshot/v1/snapshot.proto

package snapshotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Affiliates    []*Affiliate           `protobuf:"bytes,2,rep,name=affiliates,proto3" json:"affiliates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetAffiliates() []*Affiliate {
	if x != nil {
		return x.Affiliates
	}
	return nil
}

type Affiliate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Affiliate) Reset() {
	*x = Affiliate{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Affiliate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affiliate) ProtoMessage() {}

func (x *Affiliate) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Affiliate.ProtoReflect.Descriptor instead.
func (*Affiliate) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *Affiliate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Affiliate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Affiliate) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Affiliate) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Endpoint) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

var File_snapshot_v1_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1asnapshot/v1/snapshot.proto\x12\vsnapshot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\bSnapshot\x120\n" +
	"\bclusters\x18\x01 \x03(\v2\x14.snapshot.v1.ClusterR\bclusters\"Q\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\n" +
	"affiliates\x18\x02 \x03(\v2\x16.snapshot.v1.AffiliateR\n" +
	"affiliates\"\x98\x01\n" +
	"\tAffiliate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x122\n" +
	"\x06expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x123\n" +
	"\tendpoints\x18\x04 \x03(\v2\x15.snapshot.v1.EndpointR\tendpoints\"R\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x122\n" +
	"\x06expiry\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiryBLZJgithub.com/grepplabs/talos-discovery/internal/proto/snapshot/v1;snapshotv1b\x06proto3"

var (
	file_snapshot_v1_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_v1_snapshot_proto_rawDescData []byte
)

func file_snapshot_v1_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_v1_snapshot_proto_rawDesc), len(file_snapshot_v1_snapshot_proto_rawDesc)))
	})
	return file_snapshot_v1_snapshot_proto_rawDescData
}

var file_snapshot_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_snapshot_v1_snapshot_proto_goTypes = []any{
	(*Snapshot)(nil),              // 0: snapshot.v1.Snapshot
	(*Cluster)(nil),               // 1: snapshot.v1.Cluster
	(*Affiliate)(nil),             // 2: snapshot.v1.Affiliate
	(*Endpoint)(nil),              // 3: snapshot.v1.Endpoint
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_snapshot_v1_snapshot_proto_depIdxs = []int32{
	1, // 0: snapshot.v1.Snapshot.clusters:type_name -> snapshot.v1.Cluster
	2, // 1: snapshot.v1.Cluster.affiliates:type_name -> snapshot.v1.Affiliate
	4, // 2: snapshot.v1.Affiliate.expiry:type_name -> google.protobuf.Timestamp
	3, // 3: snapshot.v1.Affiliate.endpoints:type_name -> snapshot.v1.Endpoint
	4, // 4: snapshot.v1.Endpoint.expiry:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_snapshot_v1_snapshot_proto_init() }
func file_snapshot_v1_snapshot_proto_init() {
	if File_snapshot_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_v1_snapshot_proto_rawDesc), len(file_snapshot_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_v1_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_v1_snapshot_proto = out.File
	file_snapshot_v1_snapshot_proto_goTypes = nil
	file_snapshot_v1_snapshot_proto_depIdxs = nil
}
